version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # Fix for file watching in Docker on some systems