version: '3'

# services:
#   backend:
#     build: ./backend
#     ports:
#       - "5001:5000"
#     volumes:
#       - ./backend:/app
#       - ./backend/uploads:/app/uploads
#       - ./backend/trimmed:/app/trimmed

frontend:
  build: ./frontend
  volumes:
    - ./frontend:/app
    # - /app/node_modules
  ports:
    - "3000:3000"
  environment:
    - CHOKIDAR_USEPOLLING=true
  command: npm start